name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn install
        yarn build
        yarn test:ci
      env:
        CI: true
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    -
      name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME }}
        password: ${{secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push the Docker image
      uses: docker/build-push-action@v3
      with: 
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME }}/facturas-frontend-publico:latest
